# Generated by Django 5.0.7 on 2024-08-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_clients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='La direccion'),
        ),
    ]
